name: .NET

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 9.0.x
      - name: Restore dependencies
        run: |-
          dotnet restore
      - name: Build projects
        run: |-
          dotnet build
          --configuration Release
          --no-restore
      - name: Run tests
        run: |-
          dotnet test
            --configuration Release
            --no-build
      - name: Create NuGet packages
        run: |-
          dotnet pack
            --configuration Release
            --output ./artifacts
            --no-build
      - name: Publish NuGet packages
        run: |-
          for nupkg in ./artifacts/*.nupkg; do
            dotnet nuget push $nupkg
              --source https://api.nuget.org/v3/index.json
              --api-key ${{ secrets.NUGET_API_KEY }}
              --skip-duplicate
          done
